### PR TITLE
D3ASIM-3092: Upgrade d3a-interface to python 3.8.0

### PR DESCRIPTION
**Pull request by Hassan754**
# To Note
After upgrading to python 3.8.0 , flake8 tests raised error due to incompatibility.
Latest flake8 version is 3.8.4 , but after upgrading , tests failed because code was 
not compatible (We should make sure all f-strings in our code contains actually a placeholder '{}' ) https://stackoverflow.com/questions/62565979/github-action-flake8-fails-f-string-is-missing-placeholders

I had to pin flake8 version to 3.7.9 + pycodestyle + pyflakes to maintain the backward compatibility until complete code refactor .

### CODE REVIEW

**Review by fievelk — APPROVED** [review]
Looks good to me :)

**Comment by fievelk** [comment]
@Hassan754 @spyrostz 
I suggest starting merging the PRs related to python 3.8 starting from this one, since this repo is required to run CI tests for `d3a` and `d3a-api-client`.

**Comment by Hassan754** [comment]
> @Hassan754 @spyrostz
> I suggest starting merging the PRs related to python 3.8 starting from this one, since this repo is required to run CI tests for `d3a` and `d3a-api-client`.

Sure , on your signal @spyrostz

**Review by spyrostz — APPROVED** [review]
LGTM

**Comment by spyrostz** [comment]
> > @Hassan754 @spyrostz
> > I suggest starting merging the PRs related to python 3.8 starting from this one, since this repo is required to run CI tests for `d3a` and `d3a-api-client`.
> 
> Sure , on your signal @spyrostz

Please go ahead, thanks!

**Pull request merged**
