### PR TITLE
D3ASIM-3479: Changed the sign of cumulativeNetEnergyFlow to be consis…

### PR DESCRIPTION
**Pull request by hannesdiedrich**
…tent with the EnergyTradeProfile.

This has to be tested by an e2e-test. Gave up thinking about a way of testing the consistency between cumulativeNetEnergyFlow and EnergyTradeProfile.

### CODE REVIEW

**Review by spyrostz — APPROVED** [review]
LGTM, but unfortunately this will affect only new simulation runs, otherwise we need a migration to revert the sign of the field in the DB. Would be great to clarify it with frontend / Sarah.

**Comment by hannesdiedrich** [comment]
> LGTM, but unfortunately this will affect only new simulation runs, otherwise we need a migration to revert the sign of the field in the DB. Would be great to clarify it with frontend / Sarah.

Actually you are right, I save myself the hassle and dont ask, because this numbers are shown in the singularity map (as coloured circles). Will add a migration right away.

**Comment by hannesdiedrich** [comment]
> > LGTM, but unfortunately this will affect only new simulation runs, otherwise we need a migration to revert the sign of the field in the DB. Would be great to clarify it with frontend / Sarah.
> 
> Actually you are right, I save myself the hassle and dont ask, because this numbers are shown in the singularity map (as coloured circles). Will add a migration right away.

@spyrostz This is not straightforward (as you probably already know). 
I had a look into the d3a-web code now and found the `_populate_null_cumulative_net_energy_flow_entry`, but this is only run when the `cumulative_net_energy_flow` was not populated yet. I can not think of a (resource inexpensive) way to run these online migrations again for the sign change. 
If you do not have a better idea, I will try to explain this to Sarah and that they should live with this or deal with it on the frontend (for that historical runs).

**Comment by spyrostz** [comment]
> > > LGTM, but unfortunately this will affect only new simulation runs, otherwise we need a migration to revert the sign of the field in the DB. Would be great to clarify it with frontend / Sarah.
> > 
> > 
> > Actually you are right, I save myself the hassle and dont ask, because this numbers are shown in the singularity map (as coloured circles). Will add a migration right away.
> 
> @spyrostz This is not straightforward (as you probably already know).
> I had a look into the d3a-web code now and found the `_populate_null_cumulative_net_energy_flow_entry`, but this is only run when the `cumulative_net_energy_flow` was not populated yet. I can not think of a (resource inexpensive) way to run these online migrations again for the sign change.
> If you do not have a better idea, I will try to explain this to Sarah and that they should live with this or deal with it on the frontend (for that historical runs).

That's why I mentioned that we should make sure that this needs to be done before implementing it actually. In order to achieve it it is probably a better idea to create a new migration that does not recalculate the value, but only flips the sign of the existing value. Not pretty, better to be avoided unless necessary.
However, how about instead of changing it in the database, to change the sign convention in the API? That way you will be able to easily switch the sign from positive to negative, and also adapt it if the UI uses a different sign convention in the future.

**Comment by hannesdiedrich** [comment]
> > > > LGTM, but unfortunately this will affect only new simulation runs, otherwise we need a migration to revert the sign of the field in the DB. Would be great to clarify it with frontend / Sarah.
> > > 
> > > 
> > > Actually you are right, I save myself the hassle and dont ask, because this numbers are shown in the singularity map (as coloured circles). Will add a migration right away.
> > 
> > 
> > @spyrostz This is not straightforward (as you probably already know).
> > I had a look into the d3a-web code now and found the `_populate_null_cumulative_net_energy_flow_entry`, but this is only run when the `cumulative_net_energy_flow` was not populated yet. I can not think of a (resource inexpensive) way to run these online migrations again for the sign change.
> > If you do not have a better idea, I will try to explain this to Sarah and that they should live with this or deal with it on the frontend (for that historical runs).
> 
> That's why I mentioned that we should make sure that this needs to be done before implementing it actually. In order to achieve it it is probably a better idea to create a new migration that does not recalculate the value, but only flips the sign of the existing value. Not pretty, better to be avoided unless necessary.
> However, how about instead of changing it in the database, to change the sign convention in the API? That way you will be able to easily switch the sign from positive to negative, and also easily adapt it if the UI uses a different sign convention in the future.

Thanks a lot! I agree and have created the corresponding d3a-web PR: https://github.com/gridsingularity/d3a-web/pull/1337

Closing this PR now

**Pull request closed without merging**
