### PR TITLE
D3ASIM-3539: Adding PlotDescription dataclass

### PR DESCRIPTION
**Pull request by faizan2590**

### CODE REVIEW

**Review by Hassan754 — APPROVED** [review]
LGTM, however if this is not to be merged soon, you better change the base branch to [D3ASIM-3556](https://github.com/gridsingularity/d3a-interface/pull/253)

**Comment by faizan2590** [comment]
> LGTM, however if this is not to be merged soon, you better change the base branch to [D3ASIM-3556](https://github.com/gridsingularity/d3a-interface/pull/253)

As far as I know `settlement market` seems to be a priority, anyways if that PR got merged first, will take care of merge conflicts

**Comment by fievelk** [comment]
Where is this dataclass used? If it's only used in d3a, I'd recommend keeping it there.

**Comment by faizan2590** [comment]
> Where is this dataclass used? If it's only used in d3a, I'd recommend keeping it there as there is no need to add it as part of the dependencies of the other libraries.

Yes, for now its only needed for backend plots whose code logic is part of d3a repo ATM, so as you suggest will move this newly added dataclass as part of `d3a` then.

**Pull request closed without merging**
