### PR TITLE
D3ASIM-3321: Tracking area kpis using uuids.

### PR DESCRIPTION
**Pull request by faizan2590**

### CODE REVIEW

**Review by hannesdiedrich — APPROVED** [review]
You probably checked multiple times whether the UI is not braking right?
LGTM

**Review by spyrostz — APPROVED** [review]
LGTM, I also think that the UI should not break with these changes, but it is worth it to check it out before merging.

**Comment by faizan2590** [comment]
> LGTM, I also think that the UI should not break with these changes, but it is worth it to check it out before merging.

Tested to validate it

https://user-images.githubusercontent.com/33482427/109816052-98dfa480-7c30-11eb-9417-dd8ff73f521e.mov

**Review by spyrostz — APPROVED** [review]
LGTM

**Pull request merged**
