### PR TITLE
D3ASIM-3307: Fixed restoring the state of the net energy for areas th…

### PR DESCRIPTION
**Pull request by spyrostz**
…at do not support it.

### CODE REVIEW

**Review by faizan2590 — APPROVED** [review]
Thanks, LGTM

**Comment by Hassan754** [comment]
As a side task Spyros, can you add the 'status' key in `results_mapping` in `all_results` , 
in my task https://github.com/gridsingularity/d3a-web/pull/1093, I need it , I may do the update side from the d3a web .
Anyway if you think this should be handled in a new PR, it's okay

**Review by hannesdiedrich — APPROVED** [review]
LGTM

**Comment by spyrostz** [comment]
> As a side task Spyros, can you add the 'status' key in `results_mapping` in `all_results` ,
> in my task [gridsingularity/d3a-web#1093](https://github.com/gridsingularity/d3a-web/pull/1093), I need it , I may do the update side from the d3a web .
> Anyway if you think this should be handled in a new PR, it's okay

@Hassan754 for the simulation status I think it is better to retrieve it from the SimulationResults table, which includes all simulation results that are not dependent on time, but are denoting the current state of the simulation. The d3a-interface part only deals with aggregated and timeseries data. From the d3a-web you can easily poll it via SImulationResults.objects.filter(simulation_id=<sim_id>).status , however I am fairly certain that it is already fetched by the simulation_results Django app, so it is probably there already.

**Comment by Hassan754** [comment]
> > As a side task Spyros, can you add the 'status' key in `results_mapping` in `all_results` ,
> > in my task [gridsingularity/d3a-web#1093](https://github.com/gridsingularity/d3a-web/pull/1093), I need it , I may do the update side from the d3a web .
> > Anyway if you think this should be handled in a new PR, it's okay
> 
> @Hassan754 for the simulation status I think it is better to retrieve it from the SimulationResults table, which includes all simulation results that are not dependent on time, but are denoting the current state of the simulation. The d3a-interface part only deals with aggregated and timeseries data. From the d3a-web you can easily poll it via SImulationResults.objects.filter(simulation_id=<sim_id>).status , however I am fairly certain that it is already fetched by the simulation_results Django app, so it is probably there already.

@spyrostz it is indeed there as data['status'], but this is only available for the sim_resu that triggered the event
For sims in cache. this info is not there, anyway I think that I'll query them from the db

**Review by Hassan754 — APPROVED** [review]

**Comment by spyrostz** [comment]
> > > As a side task Spyros, can you add the 'status' key in `results_mapping` in `all_results` ,
> > > in my task [gridsingularity/d3a-web#1093](https://github.com/gridsingularity/d3a-web/pull/1093), I need it , I may do the update side from the d3a web .
> > > Anyway if you think this should be handled in a new PR, it's okay
> > 
> > 
> > @Hassan754 for the simulation status I think it is better to retrieve it from the SimulationResults table, which includes all simulation results that are not dependent on time, but are denoting the current state of the simulation. The d3a-interface part only deals with aggregated and timeseries data. From the d3a-web you can easily poll it via SImulationResults.objects.filter(simulation_id=<sim_id>).status , however I am fairly certain that it is already fetched by the simulation_results Django app, so it is probably there already.
> 
> @spyrostz it is indeed there as data['status'], but this is only available for the sim_resu that triggered the event
> For sims in cache. this info is not there, anyway I think that I'll query them from the db

@Hassan754  you should not need the status to be in the cache, nor read it from the DB IMO. When a simulation finishes or stops, you will immediately receive a new result set with the status "finished". Then you can purge immediately the results from the cache. 
Same goes for stopping a simulation btw, when a simulation is stopped a result set with the stopped status will be reported.

**Pull request merged**
